# Site
title: ULX Documentation
description: Official documentation for the ULX admin mod for Garry's Mod.
baseurl: /ulx-docs
permalink: /:title

# Repository
git:
  repository_url: https://github.com/Timmy/ulx-docs

# Navigation
nav:
  Users:
    - text: Introduction
      url: /
      available: true
    - text: Installation
      url: /installation
      available: true
    - text: Getting started
      url: /start
      available: true
    - text: User management
      url: /user-management
      available: true
    - text: Configuration
      url: /configuration
      available: true
    - text: Targeting players
      url: /targeting
      available: true
    - text: Backup and restore
      url: /backup-and-restore
      available: true
    - text: Reset to defaults
      url: /reset
      available: true
    - text: Tips and tricks
      url: /tips-and-tricks
      available: true
    - text: Third-party modules
      url: /third-party-modules
      available: true
  Developers:
    - text: SVN version
      url: /svn-version
      available: true
    - text: ULX module
      url: /ulx-module
      available: true
    - text: Hooks and functions
      url: /hooks-and-functions
    - text: Custom module
      url: /custom-module
    - text: Custom command
      url: /custom-command
    - text: Custom keyword
      url: /custom-keyword
    - text: Custom XGUI tab
      url: /custom-xgui-tab
  Resources:
    - text: ULX commands
      url: /ulx-commands
      available: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Build
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
exclude: ["README.md"]
